
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# HACS (Home Assistant Community Store)
hacs:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

media_player:
  - platform: yamaha_musiccast
    host: 192.168.1.158
    port: 5005
    name: "Living Room MusicCast"
  - platform: yamaha_musiccast
    host: 192.168.1.208
    port: 5005
    name: "TV MusicCast"
